### ISSUE TITLE
Update jupyter-dev to jupyter (Cori) in instructions and tutorials

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/nersc#9]
With the upcoming update of the NERSC Jupyter URL, we will need to update our tutorials and instructions accordingly.

I created this issue here since this repo seems to be the most relevant one.

**Comment by heather999** [comment]
Just posting this info from NERSC here to refer back to:
* What's changing?  For quite some time we have wanted to converge both Jupyter hubs at NERSC.  What will happen when you log in after the maintenance is that you will be directed to the console (or home page), and there will be two buttons.  One, labeled Cori, corresponds to the old jupyter-dev setup.  The other, labeled Spin, corresponds to the old jupyter.nersc.gov setup.

* For a couple weeks we will have both URLs (jupyter.nersc.gov and jupyter-dev.nersc.gov) redirect to the same hub, then we will retire the jupyter-dev.nersc.gov URL from use by users.  That is: If you are a jupyter-dev user, after the maintenance you will want to start using jupyter.nersc.gov and clicking the "Cori" button to launch a notebook on Cori.  That is the same thing as using the old jupyter-dev you know and love.  (And if you're a jupyter.nersc.gov user, you click the Spin button.)

* Why?  The jupyter-dev service has become the production service and the Spin-based jupyter service is more of a backup for use when Cori is having a maintenance (and NGF and Spin are not).  This makes that more clear.  This also helps us move Jupyter@NERSC forward as a single combined service.

* What if something goes wrong?  (Seriously, when does that ever happen?)  Well in the unlikely event that things go belly up with the converged hub, we keep the old application stacks around for a while in case we need to revert.  That would be a very short, short-notice maintenance.  We've been testing for a while so we're pretty confident the upgrade will go smoothly, but another thing we know is that users often find things wrong we never could have imagined.

**Comment by heather999** [comment]
I've made a first pass to update the Confluence pages:
https://confluence.slac.stanford.edu/display/LSSTDESC/Using+Jupyter+at+NERSC
https://confluence.slac.stanford.edu/display/LSSTDESC/DC2+Tutorial%3A+A+Step-by-step+Guide
https://confluence.slac.stanford.edu/display/LSSTDESC/Getting+Started+at+NERSC
https://confluence.slac.stanford.edu/display/LSSTDESC/DC2+Data+Product+Overview

Not sure if we should also take a look at your script @yymao ~yymao/desc/jupyter-debug.sh   Just putting this here so I don't forget.

**Comment by yymao** [comment]
Thanks, @heather999 

- No change is needed in the debug script (I created a PR to check in the script in this repo #10). 
- I fixed two other jupyter-dev occurrences in this repo #11.

**Comment by heather999** [comment]
@yymao Do we think this issue might be complete?

**Comment by yymao** [comment]
I think so. Do you think we should send an email to all members?

**Comment by heather999** [comment]
@yymao sorry just getting back to this.. Yes, an email would be a good idea.  Unfortunately, we still don't have a NERSC user mailing list (and without Charlotte Hee available any longer - I don't see how we can get that set up), but we could use the collaboration mailing list again. Do you feel that would be ok?

**Comment by yymao** [comment]
Yep I think it's ok to use the all members list.
